ifndef::imagesdir[:imagesdir: ../../images]

:numbered!:
== Über dieses Beispiel

Diese Dokumentation beschreibt die Architektur eines (fiktiven) Softwaresystems.
Es dient als Beispiel für systematische Verbesserung oder Evolution von Systemen
gemäß http://aim42.org[aim42^] und
Architekturdokumentation gemäß http://arc42.de[arc42^].


[NOTE]
====
Ähnlichkeiten mit bestehenden Systemen sind nicht beabsichtigt, aber auch nicht
ganz zufällig.

Diese Unterlagen mit den darin enthaltenen Texten und Abbildungen sind urheberrechtlich
geschützt - eine Verwendung ohne schriftliche Zustimmung des Autors ist nicht zulässig.
====

// mention author
include::../../common/authored-by.adoc[]


=== Warum "VENOM"?

_venom (Engl.): Gift, Giftigkeit, Bosheit._

Ich verwende den Begriff hier als Kurzform von "**VE**ry **NO**r**M**al System,
sozusagen als einen (fiktiven) Normalfall einer über Jahre hinweg entwickelten
und benutzten Individualsoftware.

Boshaft ist daran nur, dass die hier beschriebenen Fehler und Probleme zwar erfunden
sind, aber in der Realität natürlich in ähnlicher Form vorkommen - hoffentlich weniger
gehäuft.

Ganz normal halt... icon:smile-o[]


[small]#Das VENOM System hat nichts mit der gleichnamigen Sicherheitslücke
http://venom.crowdstrike.com/[_Virtualized Environment Neglegted Operations Manipulation_^]) zu tun, bei der Angreifer über das virtuelle Floppy-Laufwerk unbeschränkten Zugriff (_root-access_) auf den
Virtualisierungshost erhalten können.#
