
== Lösungsstrategie

Nachfolgend einige Lösungsansätze, teilweise für die vorab genannten
<<Qualitätsziele>>.

[options="header", cols="4,4"]
.Lösungsansätze für wichtige Szenarien
|===
| Szenario | Lösungsansatz
a| Entwicklungsgeschwindigkeit: Neue Features sollen möglichst schnell umgesetzt werden können:

* _einfache_ Features innerhalb von 2-3 Tagen
* _mittlere_ Features innerhalb von 5-15 Tagen
* Behebung kritischer Fehler innerhalb von 4-8 Stunden

| Integration der spezialisierten Anwendungen der zugekauften Unternehmen. 


| Kostengünstige Entwicklung
| Wiederverwendung der Anwendungen der zugekauften Unternehmen.

| Korrektheit: Es lassen sich nur sachlich/fachlich korrekte Produkte konfigurieren
| Integration eines durch externalisierte Regeln konfigurier- und erweiterbaren
Expertensystems (auf Basis der JBoss-Drools Regelengine).
 
| Langfristige Auskunftsfähigkeit: Interne und berechtigte externe Anfragen nach AP-Daten können bis zu 15 Jahre nach Erzeugung dieser Daten innerhalb von maximal 30 Sekunden beantwortet werden. 
| Speicherung sämtlicher Angebots- und Auftragsdaten auf Write-Once Datenspeichern
(zur Zeit: optische Speichermedien), so daß diese Daten niemals versehentlich gelöscht werden können.
|===


[TIP]
--
Passen die Lösungsansätze zu den Geschäftszielen von SAMM Inc. 
bzw. den <<Qualitätsziele, Qualitätszielen>> von VENOM? 
--

[WARNING]
--
Die starke Heterogenität der zugekauften Systeme führt 
zu vielfältigen Integrationsproblemen, erfordert immens breites
Know-How seitens der IT-Entwicklung, verlangsamt Entwicklungs- und Testzeiten. Die Anforderung
nach hoher Entwicklungsgeschwindigkeit ist damit aus Sicht der Fachbereiche *nicht erfüllt*.
--