
== Verteilungssicht

Der IT-Betrieb liegt komplett in der Verantwortung der Sure Data Inc.,
einer Beteiligung der SAMM Inc. Sure Data verantwortet ebenfalls die
Details der Hardware-Infrastruktur.

* IT-Entwicklung paketiert und übergibt Releases von VENOM als <<RPM>>-Pakete.
Dabei kommt <<Puppet>> zum Einsatz.
* Releases werden langfristig geplant, aktuell 4-5 _Milestone-Releases_ pro Jahr.
* Bugfixes werden ad-hoc an den Betrieb übergeben, seit 2014 fast wöchentlich.


[WARNING]
--
Aus Sicht der IT-Entwicklung dauert die Inbetriebnahme übergebener Releases
mit 7-14 Tage deutlich zu lange. Die Administratoren von Sure Data als
VENOM Betreiber hingegen klagen über mangelhafte Release- und Betriebsdokumention
sowie zu geringe Qualität. Sie müssen bei jedem Release hohe manuelle Aufwände
in Test, Detailkonfiguration und Installation investieren.  
--

[WARNING]
--
Releases sind sowohl für SAMM wie Sure Data mit ständig steigenden
manuellen Aufwänden verbunden, hochgradig fehleranfällig und für alle
Beteiligten unbefriedigend und stressig.
--



