
== Glossar und Abkürzungen



[cols="1,4" options="header"]
.Glossar
|===
|Begriff
|Definition

| AP | -> Archivierungspflicht

| Archivierungspflicht
| SAMM ist gesetzlich verpflichtet, Angebote, Aufträge und Abrechnungsinformationen
für die jeweils dafür vorgeschriebenen Zeiträume zu archivieren, ebenso
die Stammdaten gewerblicher Kunden für Projekte/Produkte mit Exportbeschränkung (->ECI).
Zur Aufbewahrung von
Angebots- und Rechnungsinformationen gelten für einige Geschäftsbereiche der SAMM
dafür Fristen von 15 Jahren.

| ATLAS
| Ein ab 2003 von der damaligen ROT Ag übernommener Spezialanbieter für 
  Software im Bereich Planung und Vermittlung von Transportleistungen
  mit unterschiedlichen Speditionen. Die Software gleichen Namens (ATLAS/2) wurde
  in VENOM integriert. Sehr erfolgreich mit öffentlichen Unternehmen und Behörden
  weltweit.

| [[BAFA]] BAFA 
| http://de.wikipedia.org/wiki/Bundesamt_f%C3%BCr_Wirtschaft_und_Ausfuhrkontrolle[Bundesamt für Wirtschaft und Außenkontrolle]

| BI 
| _business intelligence_, Verfahren und Prozesse zur Sammlung und Auswertung betriebswirtschaftlich relevanter Daten mit dem Ziel, bessere operative oder strategische Entscheidungen treffen zu können. BI wertet mit entsprechender Software Daten über das eigene Unternehmen, die Mitbewerber sowie die Marktentwicklung aus.

| CF | _customer facing_, Systeme oder Anwendungen für Kunden

| CTI | _computer telephony integration_, Integration und Koordination von Interaktionen über Telefon und Computer. Für VENOM ist das die automatische Weiterleitung bei 
sehr komplexen Produktkonfigurationen an den Telefonsupport, Scheduling von Rückrufwünschen
sowie die optionale _ask the expert_ Funktion zur Kontrolle und Überprüfung von Produkten
vor der Beauftragung.

| [[ECI]] ECI 
| _Export Control Interface_, Standardschnittstelle, über die Behörden 
 relevante Informationen über exportregulierte Projekte abrufen können, u.a. 
 Baupläne, Stücklisten, Artikelbeschreibungen, Lieferanten- und Transportdetails.

| iBOSS
| ursprüngliche Bezeichnung des _integrierten Betriebs- und Online Software Systems_,
die nach einer Petition der Mitarbeiter seit 2002 nicht mehr verwendet wird.

| Konfigurator 
| Ermöglicht Endbenutzern den Entwurf bzw. Konfiguration komplexer Produkte.
 Teilweise durch Regel- oder Expertensysteme unterstützt, teilweise auch durch telefonische Beratung.
 

| Kunden 
| Privatkunden (private cus, Benutzergruppen, Firmenkunden, Behörden (staatliche Organisationen), Organisationen (-> NPOs)

| NGO 
| _non government organization_,
  nichtstaatliche Organisationen, beispielsweise Verbände,
  Vereine, Gewerkschaften oä, die nicht
  als Unternehmen geführt werden. 

| NPO a| _non profit organization_, Hilfsorganisationen oder gemeinnützige
Organisationen/Vereine. Beispiele: 
http://www.drk.de/ueber-uns/auftrag.html[Rotes Kreuz], 
http://www.cap-anamur.org/[Cap Anamur], 
http://www.greenpeace.org/international/en/[Greenpeace]. 

| PoS 
| _Point of Sales_, der Verkaufsort von Waren. Relevant beispielsweise
für die Konfiguratoren von Apothekensystemen.

| SAMM
| Sell And Make Money. Eingetragenes Marken- und Warenzeichen (C) und (R) SAMM Inc. 

| Scoring
| Variante der Bonitätsprüfung: Scores sind Wert von 1 bis 100, der die (statistische) Wahrscheinlichkeit angibt, 
  dass ein Kredit bedient wird. Je niedriger der Wert, desto größer die Ausfallwahrscheinlichkeit. 

| Sonderkonfiguration
| Eine über den erwarteten Konfigurationsumfang hinausgehende,
in einer oder mehreren Dimensionen spezielle Konfiguration.
Beispiel: In Apotheken werden Lagerautomaten standardmässig zwischen Keller
und Erdgeschoß oder nur im Erdgeschoß gebaut. Eine Sonderkonfiguration
wäre somit die Überbrückung einer deutlich größeren Höhendifferenz.


| t&m | _time and material_, Beauftragung von Dienstleistungen nach Zeit- und/oder Aufwand.

| Validierung
a| Überprüfung einer Konfiguration nach drei Kategorien: 

* technische Korrektheit, z.B. Tragfähigkeit, Statik oä.
* juristische Korrektheit, insbesondere Einhaltung gesetzlicher Rahmenbedingungen und -><<ECI>> Compliance 
* betriebswirtschaftliche Prüfung, ob Ertrag, Risiko und
  Kundenkategorie in sinnvollen Relationen zueinander stehen.

Durchgeführt durch den <<Configuration Validator>>.

| VENOM 
| *VE*ry *NO*r*M*al system, das integrierte ERP, CRM und Abrechnungssystem der ->SAMM Inc.

|===
